config/routes.rb
Rails.application.routes.draw do
  resources :microposts
  get 'sessions/new'
  post    "login"    => "sessions#create"
  delete  "logout"   => "sessions#destroy"
  root 'homes#index'
  resources :users
  resources :homes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/micropost.rb
class Micropost < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates_length_of :password,
   :minimum => 4 ,       
   :maximum => 7 ,     
   :in => 4..7,           
   :too_short => 'long 4 to 7',
   :too_long => 'long 4 to 7'
   
   validates :name, presence: true

   validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
   :message => 'wrong format' 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper

    before_action :require_login

    def require_login
      unless logged_in?
        redirect_to sessions_new_path
      end
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    before_action :set_user, only: %i[ show ]
    skip_before_action :require_login, only: [:index]

    def index
        @homes=Home.all
    end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  # người dùng đăng nhập để chạy hành động
  before_action :set_micropost, only: %i[ show edit update destroy ]

  # GET /microposts or /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1 or /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts or /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

      if @micropost.save
        redirect_to @micropost, notice: "sssss" 
      else
        render :new, status: :unprocessable_entity 
      end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: "Micropost was successfully updated." }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: "Micropost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user= User.find_by email: params[:session][:email].downcase
    if 
      user && user.authenticate(params[:session][:password])
          flash[:success]="Đăng nhập thành công"
          check_login=true;
          log_in user
          redirect_to user
    else
      flash[:danger] = "Email/Mật khẩu không hợp lệ"
      render :new
    end
  end

  def destroy
    log_out
    flash[:success] = "Bạn đã đăng xuất"
    redirect_to homes_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  # người dùng chỉ được create user  khi không đăng nhập
  skip_before_action :require_login, only: [:new, :create]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find_by id: params[:id]
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Đăng ký thành công"
      redirect_to users_path
    else  
      flash[:success] = "Đăng kí thất bại"
      render :new
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
      if @user.update(user_params)
        redirect_to @user, notice: "User was successfully updated."
      else
        render :edit, status: :unprocessable_entity 
      end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "Đã xóa người dùng thành công." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name,:email, :password, :password_confirmation,:address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in user
      session[:user_id] = user.id
    end

    def log_out
      session.delete :user_id
    end

    #Lấy thông tin của user
    def current_user
        @current_user ||= User.find_by id: session[:user_id]
    end

  # Check available
    def logged_in?
        current_user.present?
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<%= render 'layouts/header' %>

<div class="text-center row" style="margin-top: 150px;">
    <h1>HELLO EVERYONE</h1>
    <%= link_to 'Create Account', new_user_path,class:"btn btn-primary"%>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <a><%= link_to "logođây", users_path,class:"logo" %></a>
  <div class="header-right">
    <% if logged_in? %>
        <div class="dropdown">
        <button class="dropbtn">Dropdown</button>
            <div class="dropdown-content">
                <a><%= link_to "List user", users_path,style:"margin-left: -22px;" %></a>
                <a><%= link_to "List micropos", microposts_path %></a>
                <a><%= link_to "Log out", logout_path, method: :delete %></a>
            </div>
        </div>
    <% else %>
           <div class="header-right">
                <a><%= link_to "home", root_path %></a>
                <a><%= link_to "Log in", sessions_new_path %></a>
                <a><%= link_to "Create user", users_path %></a>
           </div>
    <% end %>      
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginUser</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
   
    <section class="content" style="min-height: auto;">
      <% flash.each do |key, value| %>
        <div class="row">
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        </div>
      <% end %>
    </section>

      <%# section/ %>

    <%= yield %>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost,html: {class: "form-horizontal"}  ) do |form| %>

<div class="row">
  <div class="col-lg-offset-2">

      <div class="form-group">
        <%= form.label :content, "Content", class: "col-md-2 control-label" %>
        <div class="col-md-5">
          <%= form.text_field :content, class: "form-control", placeholder: "Enter content" %>
        </div>
      </div>

      <div class="form-group" >
        <%= form.label :user_id, "User", class: "col-md-2 control-label" %>
        <div class="col-md-5" >
          <%= form.collection_select :user_id, User.order(:id), :id, :name%>
        </div>
      </div>
      
      <div class="col-lg-offset-2 row ">
      <%= form.submit  class: "btn btn-success" %>
      <%= link_to 'Back', microposts_path ,class: "btn btn-success" %>
      </div>
  </div>
</div>

<% end %>

app/views/microposts/edit.html.erb
<%= render 'layouts/header' %>

<h1 class="title text-center">Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

app/views/microposts/index.html.erb
<%= render 'layouts/header' %>

<p id="notice"><%= notice %></p>

<div class="container">
    <div class="row">
      <h1 class="text-center title">Microposts</h1>
      <div class="col-lg-12 form-group">
         <h3><label>Welcome</label>
         <%= link_to current_user.name, user_path(current_user) %></h3>
      </div>
      <%= link_to 'Create micropost',new_micropost_path,class:"btn btn-success" %>
      <table class="table table-striped" >
        <thead>
          <tr>
            <th class="text-center">ID micropost</th>
            <th>Content</th>
            <th>User Id</th>
            <th colspan="3"></th>
          </tr>
        </thead>

         <tbody >
          <% @microposts.each do |micropost| %>
            <tr>
              <td class="text-center"><%= micropost.id %></td>
              <td><%= micropost.content %></td>
              <td><%= micropost.user_id %></td>
              <td><%= link_to 'Show', micropost %></td>
              <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
              <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
         </tbody>
        </table>

       <br>
            
    </div>
</div>

app/views/microposts/new.html.erb
<%= render 'layouts/header' %>

<h1 class="title text-center">New Micropost</h1>

<%= render 'form', micropost: @micropost %>

app/views/microposts/show.html.erb
<%= render 'layouts/header' %>

<div class="text-center" style="margin-top: 30px;" >

    <h3>
      <strong>Content:</strong>
      <%= @micropost.content %>
    </h3>

    <h3>
      <strong>User:</strong>
      <%= @micropost.user_id %>
    </h3> 

    <%= link_to 'Edit', edit_micropost_path(@micropost),class:"btn btn-success" %> 
    <%= link_to 'Back', microposts_path,class:"btn btn-success",style:"margin-left: 15px;" %>

</div>

app/views/users/_errors.html.erb
<div class="text-center">
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> </h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

   <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<%= render 'layouts/header' %>

<div class="col-lg-12 text-center">
    <h1 class="title">Edit User</h1>

    <%= render 'form', user: @user %>

    <div class="size">
        <%= link_to 'Show', @user %> |
        <%= link_to 'Back', users_path %>
    </div>
</div>

app/views/users/index.html.erb
<%= render 'layouts/header' %>

<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="title">List Users</h1>
    </div>
    <div class="col-lg-12 form-group">
      <h3><label for="">Welcome</label>
      <%= link_to current_user.name, user_path(current_user) %></h3>
    </div>
    <table class="table table-striped"  >
    
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Address</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.address %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Muốn xóa hả?' } %></td>
          </tr>
        <% end %>
      </tbody>
      
    </table>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'layouts/header' %>

<h1 class="text-center">Create User</h1>

<%= render 'errors', user: @user %>

<div class="row">
  <div class="col-lg-offset-2">
    <%= form_for @user, html: {class: "form-horizontal"} do |f| %>

      <div class="form-group">
        <%= f.label :name, "Name", class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter user name" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :address, "Address", class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.text_field :address, class: "form-control", placeholder: "Enter address" %>
        </div>
      </div>

       <div class="form-group">
        <%= f.label :email, "Email", class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.text_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password, "Password", class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Password Confirmation", class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password confirmation" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-lg-offset-4">
          <%= f.submit "Register", class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/header' %>



<div class="text-center" >
    <h2> <label>Hello: <%= @user.name %></label></h2>
    <%= link_to "List Users", users_path %>
</div>